name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - name: Install pnpm with Volta
        run: volta install pnpm # Instruct Volta to install pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run lint
        run: pnpm run lint --if-present
      - name: Run prettier check
        run: pnpm run prettier:check --if-present
      - name: Run tests
        run: pnpm test
      - name: Run build
        run: pnpm run build --if-present
